[window]
title = "Scribble"
width = 1024
height = 768

[vulkan]
validation_enabled = true
max_frames_in_flight = 2
max_vertices = 10000
staging_buffer_vertex_count = 500

[shaders]
vertex = "shaders/vert.spv"
fragment = "shaders/frag.spv"
